name: solar_community_icons
description: "Flutter package providing Solar community icons in bold and linear styles."

icon: assets/logo.png
homepage: https://github.com/ardev-dev/solar_community_icons
repository: https://github.com/ardev-dev/solar_community_icons
issue_tracker: https://github.com/ardev-dev/solar_community_icons/issues

version: 1.1.1

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  very_good_analysis: ^6.0.0
  icon_generator: ^4.0.3

flutter:
  fonts:
    - family: SolarCommunityBoldIcons
      fonts:
        - asset: assets/fonts/solar_bold_icons.ttf
    - family: SolarCommunityLinearIcons
      fonts:
        - asset: assets/fonts/solar_linear_icons.ttf
